/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Response detailing why a request was rejected. Adheres to the [RFC-7807](https://datatracker.ietf.org/doc/html/rfc7807) standard (colloquially known as \"Problem JSON\") for the response format. 
 *
 * @param status HTTP status code of the problem response.
 * @param type A URN (Uniform Resource Name) identifying the type of the problem.
 * @param title The underlying reason for the problem.
 * @param detail A longer and comprehensive description of the problem. May be `null` if not available.
 */
@Serializable

data class ApiProblem (

    /* HTTP status code of the problem response. */
    @SerialName(value = "status")
    val status: kotlin.Int,

    /* A URN (Uniform Resource Name) identifying the type of the problem. */
    @SerialName(value = "type")
    val type: kotlin.String,

    /* The underlying reason for the problem. */
    @SerialName(value = "title")
    val title: kotlin.String,

    /* A longer and comprehensive description of the problem. May be `null` if not available. */
    @SerialName(value = "detail")
    val detail: kotlin.String? = null

)

