/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Bazel work unit.
 *
 * @param packageName The name of the Bazel package.
 * @param targetName The name of the Bazel target.
 */
@Serializable

data class BazelWorkUnit (

    /* The name of the Bazel package. */
    @SerialName(value = "packageName")
    val packageName: kotlin.String,

    /* The name of the Bazel target. */
    @SerialName(value = "targetName")
    val targetName: kotlin.String

)

