/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The environment where the build is executed.
 *
 * @param operatingSystem Operating system of the build machine.
 * @param numberOfCpuCores Number of cores available to the build JVM.
 * @param jreVersion Version of the Java runtime executing the build.
 * @param jvmVersion Version of the Java Virtual Machine executing the build.
 * @param jvmMaxMemoryHeapSize Maximum heap memory available to the build JVM in bytes.
 * @param jvmLocale The locale of the JVM executing the build.
 * @param username Operating system username of the build user. `null` if no username is captured.
 * @param jvmCharset The default charset of the JVM executing the build. `null` if capturing is not possible.
 * @param publicHostname The hostname of the build machine, as seen on the network. `null` if capturing is not possible.
 * @param localHostname The hostname of the build machine, as specified by itself. `null` if capturing is not possible.
 * @param localIpAddresses The local IP addresses of the build machine. `null` if capturing is not possible.
 */
@Serializable

data class BuildAttributesEnvironment (

    /* Operating system of the build machine. */
    @SerialName(value = "operatingSystem")
    val operatingSystem: kotlin.String,

    /* Number of cores available to the build JVM. */
    @SerialName(value = "numberOfCpuCores")
    val numberOfCpuCores: kotlin.Int,

    /* Version of the Java runtime executing the build. */
    @SerialName(value = "jreVersion")
    val jreVersion: kotlin.String,

    /* Version of the Java Virtual Machine executing the build. */
    @SerialName(value = "jvmVersion")
    val jvmVersion: kotlin.String,

    /* Maximum heap memory available to the build JVM in bytes. */
    @SerialName(value = "jvmMaxMemoryHeapSize")
    val jvmMaxMemoryHeapSize: kotlin.Long,

    /* The locale of the JVM executing the build. */
    @SerialName(value = "jvmLocale")
    val jvmLocale: kotlin.String,

    /* Operating system username of the build user. `null` if no username is captured. */
    @SerialName(value = "username")
    val username: kotlin.String? = null,

    /* The default charset of the JVM executing the build. `null` if capturing is not possible. */
    @SerialName(value = "jvmCharset")
    val jvmCharset: kotlin.String? = null,

    /* The hostname of the build machine, as seen on the network. `null` if capturing is not possible. */
    @SerialName(value = "publicHostname")
    val publicHostname: kotlin.String? = null,

    /* The hostname of the build machine, as specified by itself. `null` if capturing is not possible. */
    @SerialName(value = "localHostname")
    val localHostname: kotlin.String? = null,

    /* The local IP addresses of the build machine. `null` if capturing is not possible. */
    @SerialName(value = "localIpAddresses")
    val localIpAddresses: kotlin.collections.List<kotlin.String>? = null

)

