/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Build Scan value.
 *
 * @param name The name of the Build Scan value.
 * @param `value` The value of the Build Scan value. `null` if the Build Scan value is not set.
 */
@Serializable

data class BuildAttributesValue (

    /* The name of the Build Scan value. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The value of the Build Scan value. `null` if the Build Scan value is not set. */
    @SerialName(value = "value")
    val `value`: kotlin.String? = null

)

