/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param models The list of build models to return in the response for each build. If not provided, no models are returned. 
 * @param allModels Whether to include all build models for the build. If set to `true`, the value of the `models` parameter is ignored. 
 * @param availabilityWaitTimeoutSecs The time in seconds the server should wait for ingestion before returning a wait timeout response.
 */
@Serializable

data class BuildQuery (

    /* The list of build models to return in the response for each build. If not provided, no models are returned.  */
    @SerialName(value = "models")
    val models: kotlin.collections.List<@Contextual BuildModelName>? = null,

    /* Whether to include all build models for the build. If set to `true`, the value of the `models` parameter is ignored.  */
    @SerialName(value = "allModels")
    val allModels: kotlin.Boolean? = false,

    /* The time in seconds the server should wait for ingestion before returning a wait timeout response. */
    @SerialName(value = "availabilityWaitTimeoutSecs")
    val availabilityWaitTimeoutSecs: kotlin.Int? = null

)

