/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Build Scan IDs for builds that contain tests with outcomes.
 *
 * @param passed The BuildIds of 'Passed' outcomes.
 * @param failed The Build Scan IDs of 'Failed' outcomes.
 * @param skipped The BuildIds of 'Skipped' outcomes.
 * @param flaky The BuildIds of 'Flaky' outcomes.
 * @param notSelected The BuildIds of 'Not Selected' outcomes.
 */
@Serializable

data class BuildScanIdsByOutcome (

    /* The BuildIds of 'Passed' outcomes. */
    @SerialName(value = "passed")
    val passed: kotlin.collections.List<kotlin.String>,

    /* The Build Scan IDs of 'Failed' outcomes. */
    @SerialName(value = "failed")
    val failed: kotlin.collections.List<kotlin.String>,

    /* The BuildIds of 'Skipped' outcomes. */
    @SerialName(value = "skipped")
    val skipped: kotlin.collections.List<kotlin.String>,

    /* The BuildIds of 'Flaky' outcomes. */
    @SerialName(value = "flaky")
    val flaky: kotlin.collections.List<kotlin.String>,

    /* The BuildIds of 'Not Selected' outcomes. */
    @SerialName(value = "notSelected")
    val notSelected: kotlin.collections.List<kotlin.String>

)

