/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of Maven modules, or a report of a problem encountered.
 *
 * @param problem 
 * @param model List of Maven modules including structural relationships.
 */
@Serializable

data class BuildModelsMavenModules (

    @SerialName(value = "problem")
    val problem: ApiProblem? = null,

    /* List of Maven modules including structural relationships. */
    @SerialName(value = "model")
    val model: kotlin.collections.List<MavenModule>? = null

)

