/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Build Scan link.
 *
 * @param label The label of the Build Scan link.
 * @param url The url  of the Build Scan link.
 */
@Serializable

data class BuildAttributesLink (

    /* The label of the Build Scan link. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* The url  of the Build Scan link. */
    @SerialName(value = "url")
    val url: kotlin.String

)

