/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param availabilityWaitTimeoutSecs The time in seconds the server should wait for ingestion before returning a wait timeout response.
 */
@Serializable

data class BuildModelQuery (

    /* The time in seconds the server should wait for ingestion before returning a wait timeout response. */
    @SerialName(value = "availabilityWaitTimeoutSecs")
    val availabilityWaitTimeoutSecs: kotlin.Int? = null

)

