/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Optional requested models associated with the build.
 *
 * @param gradleAttributes 
 * @param gradleBuildCachePerformance 
 * @param gradleProjects 
 * @param gradleNetworkActivity 
 * @param gradleArtifactTransformExecutions 
 * @param gradleDeprecations 
 * @param mavenAttributes 
 * @param mavenBuildCachePerformance 
 * @param mavenModules 
 * @param mavenDependencyResolution 
 */
@Serializable

data class BuildModels (

    @SerialName(value = "gradleAttributes")
    val gradleAttributes: BuildModelsGradleAttributes? = null,

    @SerialName(value = "gradleBuildCachePerformance")
    val gradleBuildCachePerformance: BuildModelsGradleBuildCachePerformance? = null,

    @SerialName(value = "gradleProjects")
    val gradleProjects: BuildModelsGradleProjects? = null,

    @SerialName(value = "gradleNetworkActivity")
    val gradleNetworkActivity: BuildModelsGradleNetworkActivity? = null,

    @SerialName(value = "gradleArtifactTransformExecutions")
    val gradleArtifactTransformExecutions: BuildModelsGradleArtifactTransformExecutions? = null,

    @SerialName(value = "gradleDeprecations")
    val gradleDeprecations: BuildModelsGradleDeprecations? = null,

    @SerialName(value = "mavenAttributes")
    val mavenAttributes: BuildModelsMavenAttributes? = null,

    @SerialName(value = "mavenBuildCachePerformance")
    val mavenBuildCachePerformance: BuildModelsMavenBuildCachePerformance? = null,

    @SerialName(value = "mavenModules")
    val mavenModules: BuildModelsMavenModules? = null,

    @SerialName(value = "mavenDependencyResolution")
    val mavenDependencyResolution: BuildModelsMavenDependencyResolution? = null

)

