/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * **This property is deprecated, use `develocitySettings` instead.** Settings for Develocity. 
 *
 * @param backgroundPublicationEnabled Indicates whether background Build Scan publication is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.4`. See https://gradle.com/help/gradle-plugin-configuring-background-uploading.
 * @param buildOutputCapturingEnabled Indicates whether build logging output capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.7`. See https://gradle.com/help/gradle-plugin-capturing-build-and-test-outputs.
 * @param taskInputsFileCapturingEnabled Indicates whether task input file snapshots capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `2.1`. See https://gradle.com/help/gradle-plugin-capturing-task-input-files.
 * @param testOutputCapturingEnabled Indicates whether test logging output capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.7`. See https://gradle.com/help/gradle-plugin-capturing-build-and-test-outputs.
 */
@Serializable
@Deprecated(message = "This schema is deprecated.")

data class GradleGradleEnterpriseSettings (

    /* Indicates whether background Build Scan publication is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.4`. See https://gradle.com/help/gradle-plugin-configuring-background-uploading. */
    @SerialName(value = "backgroundPublicationEnabled")
    val backgroundPublicationEnabled: kotlin.Boolean? = null,

    /* Indicates whether build logging output capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.7`. See https://gradle.com/help/gradle-plugin-capturing-build-and-test-outputs. */
    @SerialName(value = "buildOutputCapturingEnabled")
    val buildOutputCapturingEnabled: kotlin.Boolean? = null,

    /* Indicates whether task input file snapshots capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `2.1`. See https://gradle.com/help/gradle-plugin-capturing-task-input-files. */
    @SerialName(value = "taskInputsFileCapturingEnabled")
    val taskInputsFileCapturingEnabled: kotlin.Boolean? = null,

    /* Indicates whether test logging output capturing is enabled for the build. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `3.7`. See https://gradle.com/help/gradle-plugin-capturing-build-and-test-outputs. */
    @SerialName(value = "testOutputCapturingEnabled")
    val testOutputCapturingEnabled: kotlin.Boolean? = null

)

