/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param type The type of the deprecation owner:   * `plugin` - The owner of the deprecation is a plugin.   * `script` - The owner of the deprecation is a script.   * `task` - The owner of the deprecation is a task.   * `unknown` - Unknown deprecation owner type when none of the other options match. 
 * @param location The location of the deprecation usage. Can be a plugin id, task path, script file path, script URI. `null` if the owner type is unknown.
 */
@Serializable

data class GradleDeprecationOwner (

    /* The type of the deprecation owner:   * `plugin` - The owner of the deprecation is a plugin.   * `script` - The owner of the deprecation is a script.   * `task` - The owner of the deprecation is a task.   * `unknown` - Unknown deprecation owner type when none of the other options match.  */
    @SerialName(value = "type")
    val type: GradleDeprecationOwner.Type,

    /* The location of the deprecation usage. Can be a plugin id, task path, script file path, script URI. `null` if the owner type is unknown. */
    @SerialName(value = "location")
    val location: kotlin.String? = null

) {

    /**
     * The type of the deprecation owner:   * `plugin` - The owner of the deprecation is a plugin.   * `script` - The owner of the deprecation is a script.   * `task` - The owner of the deprecation is a task.   * `unknown` - Unknown deprecation owner type when none of the other options match. 
     *
     * Values: PLUGIN,SCRIPT,TASK,UNKNOWN
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "plugin") PLUGIN("plugin"),
        @SerialName(value = "script") SCRIPT("script"),
        @SerialName(value = "task") TASK("task"),
        @SerialName(value = "unknown") UNKNOWN("unknown");
    }
}

