/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the local and remote build caches used in the build. `null` if the build cache is globally disabled.
 *
 * @param local 
 * @param remote 
 * @param overhead 
 */
@Serializable

data class GradleBuildCachePerformanceBuildCaches (

    @SerialName(value = "local")
    val local: GradleBuildCachePerformanceBuildCacheLocalInfo,

    @SerialName(value = "remote")
    val remote: GradleBuildCachePerformanceBuildCacheRemoteInfo,

    @SerialName(value = "overhead")
    val overhead: GradleBuildCachePerformanceBuildCacheOverhead

)

