/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param summary The description of the deprecation.
 * @param removalDetails The details about when the deprecated feature will be removed from Gradle.
 * @param usages List of usages of this deprecation.
 * @param advice The advice on how to avoid using the deprecated feature. `null` when no advice is available.
 * @param documentationUrl The external url pointing to some documentation about the deprecation. `null` for older Gradle/plugin combination or certain deprecation notices.
 */
@Serializable

data class GradleDeprecationEntry (

    /* The description of the deprecation. */
    @SerialName(value = "summary")
    val summary: kotlin.String,

    /* The details about when the deprecated feature will be removed from Gradle. */
    @SerialName(value = "removalDetails")
    val removalDetails: kotlin.String,

    /* List of usages of this deprecation. */
    @SerialName(value = "usages")
    val usages: kotlin.collections.List<GradleDeprecationUsage>,

    /* The advice on how to avoid using the deprecated feature. `null` when no advice is available. */
    @SerialName(value = "advice")
    val advice: kotlin.String? = null,

    /* The external url pointing to some documentation about the deprecation. `null` for older Gradle/plugin combination or certain deprecation notices. */
    @SerialName(value = "documentationUrl")
    val documentationUrl: kotlin.String? = null

)

