/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param owner 
 * @param contextualAdvice Advice on how to avoid using the deprecated feature, that is specific to this particular usage. `null` when no advice is available.
 */
@Serializable

data class GradleDeprecationUsage (

    @SerialName(value = "owner")
    val owner: GradleDeprecationOwner,

    /* Advice on how to avoid using the deprecated feature, that is specific to this particular usage. `null` when no advice is available. */
    @SerialName(value = "contextualAdvice")
    val contextualAdvice: kotlin.String? = null

)

