/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Gradle build options for this build.
 *
 * @param configurationOnDemandEnabled Indicates whether configuration on demand mode is enabled for the build. See https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand.
 * @param continuousBuildEnabled Indicates whether continuous build mode is running for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continuous_build.
 * @param continueOnFailureEnabled Indicates whether continue on failure mode is set for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continue_build_on_failure.
 * @param daemonEnabled Indicates whether the build is run with the Gradle Daemon. See https://docs.gradle.org/current/userguide/gradle_daemon.html.
 * @param dryRunEnabled Indicates whether the dry run flag is set for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_execution_options.
 * @param excludedTasks The list of excluded tasks. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line.
 * @param maxNumberOfGradleWorkers The maximum number of build workers used to run the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_performance.
 * @param offlineModeEnabled Indicates whether the offline mode is set for the build. See https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:offline-mode.
 * @param parallelProjectExecutionEnabled Indicates whether parallel project execution is enabled for the build. See https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:parallel_execution.
 * @param refreshDependenciesEnabled Indicates whether the build is set to refresh all dependencies in the dependency cache. See https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:refreshing-dependencies.
 * @param rerunTasksEnabled Indicates whether the build is forced to run all the tasks, ignoring any up-to-date checks. https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks.
 * @param buildCacheEnabled Indicates whether the build cache is enabled for the build. `null` if Gradle version is < `3.1` or Develocity Gradle plugin version is < `1.3`. See https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#isBuildCacheEnabled--.
 * @param configurationCacheEnabled Indicates whether the configuration cache is enabled for the build. `null` if Gradle version is < `6.6` or Develocity Gradle plugin version is < `3.4`. See https://docs.gradle.org/current/userguide/configuration_cache.html.
 * @param fileSystemWatchingEnabled Indicates whether file system watching is enabled for the build. `null` if Gradle version is < `6.6` or Develocity Gradle plugin version is < `3.4`. See https://docs.gradle.org/current/userguide/file_system_watching.html.
 */
@Serializable

data class GradleBuildOptions (

    /* Indicates whether configuration on demand mode is enabled for the build. See https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand. */
    @SerialName(value = "configurationOnDemandEnabled")
    val configurationOnDemandEnabled: kotlin.Boolean,

    /* Indicates whether continuous build mode is running for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continuous_build. */
    @SerialName(value = "continuousBuildEnabled")
    val continuousBuildEnabled: kotlin.Boolean,

    /* Indicates whether continue on failure mode is set for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continue_build_on_failure. */
    @SerialName(value = "continueOnFailureEnabled")
    val continueOnFailureEnabled: kotlin.Boolean,

    /* Indicates whether the build is run with the Gradle Daemon. See https://docs.gradle.org/current/userguide/gradle_daemon.html. */
    @SerialName(value = "daemonEnabled")
    val daemonEnabled: kotlin.Boolean,

    /* Indicates whether the dry run flag is set for the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_execution_options. */
    @SerialName(value = "dryRunEnabled")
    val dryRunEnabled: kotlin.Boolean,

    /* The list of excluded tasks. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line. */
    @SerialName(value = "excludedTasks")
    val excludedTasks: kotlin.collections.List<kotlin.String>,

    /* The maximum number of build workers used to run the build. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_performance. */
    @SerialName(value = "maxNumberOfGradleWorkers")
    val maxNumberOfGradleWorkers: kotlin.Int,

    /* Indicates whether the offline mode is set for the build. See https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:offline-mode. */
    @SerialName(value = "offlineModeEnabled")
    val offlineModeEnabled: kotlin.Boolean,

    /* Indicates whether parallel project execution is enabled for the build. See https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:parallel_execution. */
    @SerialName(value = "parallelProjectExecutionEnabled")
    val parallelProjectExecutionEnabled: kotlin.Boolean,

    /* Indicates whether the build is set to refresh all dependencies in the dependency cache. See https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:refreshing-dependencies. */
    @SerialName(value = "refreshDependenciesEnabled")
    val refreshDependenciesEnabled: kotlin.Boolean,

    /* Indicates whether the build is forced to run all the tasks, ignoring any up-to-date checks. https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks. */
    @SerialName(value = "rerunTasksEnabled")
    val rerunTasksEnabled: kotlin.Boolean,

    /* Indicates whether the build cache is enabled for the build. `null` if Gradle version is < `3.1` or Develocity Gradle plugin version is < `1.3`. See https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#isBuildCacheEnabled--. */
    @SerialName(value = "buildCacheEnabled")
    val buildCacheEnabled: kotlin.Boolean? = null,

    /* Indicates whether the configuration cache is enabled for the build. `null` if Gradle version is < `6.6` or Develocity Gradle plugin version is < `3.4`. See https://docs.gradle.org/current/userguide/configuration_cache.html. */
    @SerialName(value = "configurationCacheEnabled")
    val configurationCacheEnabled: kotlin.Boolean? = null,

    /* Indicates whether file system watching is enabled for the build. `null` if Gradle version is < `6.6` or Develocity Gradle plugin version is < `3.4`. See https://docs.gradle.org/current/userguide/file_system_watching.html. */
    @SerialName(value = "fileSystemWatchingEnabled")
    val fileSystemWatchingEnabled: kotlin.Boolean? = null

)

