/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the network activity of the build. It includes network activity during dependency resolution, java toolchain downloads, etc. For a comprehensive list see the Build Scan.
 *
 * @param networkRequestCount This represents the total count of network requests.
 * @param serialNetworkRequestTime The duration in milliseconds representing the sum of times for potentially parallel network requests. It does not reflect wall clock time but offers a rough estimation of network activity.
 * @param fileDownloadSize The total number of bytes downloaded for dependencies. It accounts only for the bytes of the files (e.g. POMs, JARs) downloaded and not the total network transfer.
 * @param fileDownloadCount The total number of successfully downloaded files.
 * @param wallClockNetworkRequestTime The estimate in milliseconds representing the wall clock time spent on network requests during the current build. It is calculated by comparing the critical path within non-execution and execution phases with and without network requests, converted to wall clock time. This is null when Gradle version is lower than 6.2 or the Develocity plugin version is lower than 3.12. 
 */
@Serializable

data class GradleNetworkActivity (

    /* This represents the total count of network requests. */
    @SerialName(value = "networkRequestCount")
    val networkRequestCount: kotlin.Long,

    /* The duration in milliseconds representing the sum of times for potentially parallel network requests. It does not reflect wall clock time but offers a rough estimation of network activity. */
    @SerialName(value = "serialNetworkRequestTime")
    val serialNetworkRequestTime: kotlin.Long,

    /* The total number of bytes downloaded for dependencies. It accounts only for the bytes of the files (e.g. POMs, JARs) downloaded and not the total network transfer. */
    @SerialName(value = "fileDownloadSize")
    val fileDownloadSize: kotlin.Long,

    /* The total number of successfully downloaded files. */
    @SerialName(value = "fileDownloadCount")
    val fileDownloadCount: kotlin.Long,

    /* The estimate in milliseconds representing the wall clock time spent on network requests during the current build. It is calculated by comparing the critical path within non-execution and execution phases with and without network requests, converted to wall clock time. This is null when Gradle version is lower than 6.2 or the Develocity plugin version is lower than 3.12.  */
    @SerialName(value = "wallClockNetworkRequestTime")
    val wallClockNetworkRequestTime: kotlin.Long? = null

)

