/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param artifactTransformExecutions A list of executed artifact transforms with performance related information. `null` if artifact transform execution capturing is not supported.
 */
@Serializable

data class GradleArtifactTransformExecutions (

    /* A list of executed artifact transforms with performance related information. `null` if artifact transform execution capturing is not supported. */
    @SerialName(value = "artifactTransformExecutions")
    val artifactTransformExecutions: kotlin.collections.List<GradleArtifactTransformExecutionEntry>? = null

)

