/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Gradle work unit.
 *
 * @param projectName The name of the Gradle project.
 * @param taskPath The path of the Gradle task.
 */
@Serializable

data class GradleWorkUnit (

    /* The name of the Gradle project. */
    @SerialName(value = "projectName")
    val projectName: kotlin.String,

    /* The path of the Gradle task. */
    @SerialName(value = "taskPath")
    val taskPath: kotlin.String

)

