/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Gradle project.
 *
 * @param name The name of the project.
 * @param path The path of the project.
 * @param parent The index of the parent of this Gradle project in the GradleProjects array. `null` if this project has no parent (i.e. root project of a build).
 */
@Serializable

data class GradleProject (

    /* The name of the project. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The path of the project. */
    @SerialName(value = "path")
    val path: kotlin.String,

    /* The index of the parent of this Gradle project in the GradleProjects array. `null` if this project has no parent (i.e. root project of a build). */
    @SerialName(value = "parent")
    val parent: kotlin.Int? = null

)

