/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param deprecations A list of Gradle Build Tool deprecations with details and usage information. `null` if deprecation capturing is not supported.
 */
@Serializable

data class GradleDeprecations (

    /* A list of Gradle Build Tool deprecations with details and usage information. `null` if deprecation capturing is not supported. */
    @SerialName(value = "deprecations")
    val deprecations: kotlin.collections.List<GradleDeprecationEntry>? = null

)

