/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param name The name of the attribute.
 * @param from The input attribute value.
 * @param to The requested attributed value.
 */
@Serializable

data class GradleArtifactTransformAttribute (

    /* The name of the attribute. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The input attribute value. */
    @SerialName(value = "from")
    val from: kotlin.String,

    /* The requested attributed value. */
    @SerialName(value = "to")
    val to: kotlin.String

)

