/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param artifactTransformExecutionName Artifact transform execution name.
 * @param transformActionType The fully qualified class name of the artifact transform action.
 * @param inputArtifactName The name of the input artifact transformed by this transform.
 * @param changedAttributes The list of changed attributes merged from all transform execution requests.
 * @param outcome The outcome of this artifact transform execution:   * `failed` - Artifact transform execution which failed   * `success` - Artifact transform execution which was successfully executed   * `from_cache` - Artifact transform execution which was taken from cache   * `up_to_date` - Artifact transform execution which was up-to-date   * `unknown` - Artifact transform execution whose outcome is unknown   * `skipped` - Artifact transform execution which was skipped. **This is not emitted anymore, replaced by `up_to_date`.** 
 * @param avoidanceOutcome The avoidance outcome of this artifact transform execution with respect to performance:   * `avoided_up_to_date` - Artifact transform execution whose execution is avoided due to build incrementalism   * `avoided_from_local_cache` - Artifact transform execution whose execution is avoided due to reusing a local build cache entry   * `avoided_from_remote_cache` - Artifact transform execution whose execution is avoided due to reusing a remote build cache entry   * `executed_cacheable` - Artifact transform execution which is executed but is cacheable   * `executed_not_cacheable` - Artifact transform execution which is executed but is not cacheable   * `executed_unknown_cacheability` - Artifact transform execution which is executed and whose cacheability can not be determined   * `avoided_unknown_reason` - Artifact transform execution which was avoided for an unknown reason   * `skipped` - Skipped artifact transform execution. **This is not emitted anymore, replaced by `up_to_date`.** 
 * @param duration The artifact transform execution duration in milliseconds.
 * @param fingerprintingDuration The artifact transform execution fingerprinting duration in milliseconds. This duration is part of the complete artifact transform execution duration. `null` if the artifact transform is not fingerprinted.
 * @param avoidanceSavings The artifact transform execution avoidance savings in milliseconds, which can be negative. Negative values indicate that it takes more time to reuse outputs than it did to create them originally. `null` if the information is not available.
 * @param nonCacheabilityCategory The category of the non-cacheability reason:   * `build_cache_not_enabled` - Caching is not enabled for the build   * `disabled_to_ensure_correctness` - The artifact transform failed validation   * `not_cacheable` - Caching is not enabled for this artifact transform   * `unknown` - Reason for disabled caching is not known  `null` when the artifact transform execution is cacheable 
 * @param nonCacheabilityReason The human-readable reason for a non-cacheable artifact transform execution. `null` when the artifact transform execution is cacheable.
 * @param cacheArtifactSize The number of bytes of the produced or consumed cache artifact. For an artifact transform execution where the outputs are successfully stored to a local or remote cache, this is the size of the stored cache artifact. For an artifact transform execution execution where the outputs are successfully loaded from a local or remote cache, this is the size of the loaded cache artifact. `null` if the  an artifact transform execution is not cacheable, or if the attempt to store or load the artifact from cache does not succeed. 
 * @param cacheArtifactRejectedReason The reason why the cache artifact is rejected:   * `artifact_size_too_large` - The size of the artifact is larger than the remote build cache can accept.  The value is `null` if the transform execution is not cacheable, or if the attempt to store the artifact does not succeed. 
 * @param skipReasonMessage The detailed reason why the transform execution is skipped. `null` if the transform execution is not skipped.
 * @param cacheKey The build cache key. `null` if no build cache key was computed.
 */
@Serializable

data class GradleArtifactTransformExecutionEntry (

    /* Artifact transform execution name. */
    @SerialName(value = "artifactTransformExecutionName")
    val artifactTransformExecutionName: kotlin.String,

    /* The fully qualified class name of the artifact transform action. */
    @SerialName(value = "transformActionType")
    val transformActionType: kotlin.String,

    /* The name of the input artifact transformed by this transform. */
    @SerialName(value = "inputArtifactName")
    val inputArtifactName: kotlin.String,

    /* The list of changed attributes merged from all transform execution requests. */
    @SerialName(value = "changedAttributes")
    val changedAttributes: kotlin.collections.List<GradleArtifactTransformAttribute>,

    /* The outcome of this artifact transform execution:   * `failed` - Artifact transform execution which failed   * `success` - Artifact transform execution which was successfully executed   * `from_cache` - Artifact transform execution which was taken from cache   * `up_to_date` - Artifact transform execution which was up-to-date   * `unknown` - Artifact transform execution whose outcome is unknown   * `skipped` - Artifact transform execution which was skipped. **This is not emitted anymore, replaced by `up_to_date`.**  */
    @SerialName(value = "outcome")
    val outcome: GradleArtifactTransformExecutionEntry.Outcome,

    /* The avoidance outcome of this artifact transform execution with respect to performance:   * `avoided_up_to_date` - Artifact transform execution whose execution is avoided due to build incrementalism   * `avoided_from_local_cache` - Artifact transform execution whose execution is avoided due to reusing a local build cache entry   * `avoided_from_remote_cache` - Artifact transform execution whose execution is avoided due to reusing a remote build cache entry   * `executed_cacheable` - Artifact transform execution which is executed but is cacheable   * `executed_not_cacheable` - Artifact transform execution which is executed but is not cacheable   * `executed_unknown_cacheability` - Artifact transform execution which is executed and whose cacheability can not be determined   * `avoided_unknown_reason` - Artifact transform execution which was avoided for an unknown reason   * `skipped` - Skipped artifact transform execution. **This is not emitted anymore, replaced by `up_to_date`.**  */
    @SerialName(value = "avoidanceOutcome")
    val avoidanceOutcome: GradleArtifactTransformExecutionEntry.AvoidanceOutcome,

    /* The artifact transform execution duration in milliseconds. */
    @SerialName(value = "duration")
    val duration: kotlin.Long,

    /* The artifact transform execution fingerprinting duration in milliseconds. This duration is part of the complete artifact transform execution duration. `null` if the artifact transform is not fingerprinted. */
    @SerialName(value = "fingerprintingDuration")
    val fingerprintingDuration: kotlin.Long? = null,

    /* The artifact transform execution avoidance savings in milliseconds, which can be negative. Negative values indicate that it takes more time to reuse outputs than it did to create them originally. `null` if the information is not available. */
    @SerialName(value = "avoidanceSavings")
    val avoidanceSavings: kotlin.Long? = null,

    /* The category of the non-cacheability reason:   * `build_cache_not_enabled` - Caching is not enabled for the build   * `disabled_to_ensure_correctness` - The artifact transform failed validation   * `not_cacheable` - Caching is not enabled for this artifact transform   * `unknown` - Reason for disabled caching is not known  `null` when the artifact transform execution is cacheable  */
    @SerialName(value = "nonCacheabilityCategory")
    val nonCacheabilityCategory: GradleArtifactTransformExecutionEntry.NonCacheabilityCategory? = null,

    /* The human-readable reason for a non-cacheable artifact transform execution. `null` when the artifact transform execution is cacheable. */
    @SerialName(value = "nonCacheabilityReason")
    val nonCacheabilityReason: kotlin.String? = null,

    /* The number of bytes of the produced or consumed cache artifact. For an artifact transform execution where the outputs are successfully stored to a local or remote cache, this is the size of the stored cache artifact. For an artifact transform execution execution where the outputs are successfully loaded from a local or remote cache, this is the size of the loaded cache artifact. `null` if the  an artifact transform execution is not cacheable, or if the attempt to store or load the artifact from cache does not succeed.  */
    @SerialName(value = "cacheArtifactSize")
    val cacheArtifactSize: kotlin.Long? = null,

    /* The reason why the cache artifact is rejected:   * `artifact_size_too_large` - The size of the artifact is larger than the remote build cache can accept.  The value is `null` if the transform execution is not cacheable, or if the attempt to store the artifact does not succeed.  */
    @SerialName(value = "cacheArtifactRejectedReason")
    val cacheArtifactRejectedReason: GradleArtifactTransformExecutionEntry.CacheArtifactRejectedReason? = null,

    /* The detailed reason why the transform execution is skipped. `null` if the transform execution is not skipped. */
    @SerialName(value = "skipReasonMessage")
    val skipReasonMessage: kotlin.String? = null,

    /* The build cache key. `null` if no build cache key was computed. */
    @SerialName(value = "cacheKey")
    val cacheKey: kotlin.String? = null

) {

    /**
     * The outcome of this artifact transform execution:   * `failed` - Artifact transform execution which failed   * `success` - Artifact transform execution which was successfully executed   * `from_cache` - Artifact transform execution which was taken from cache   * `up_to_date` - Artifact transform execution which was up-to-date   * `unknown` - Artifact transform execution whose outcome is unknown   * `skipped` - Artifact transform execution which was skipped. **This is not emitted anymore, replaced by `up_to_date`.** 
     *
     * Values: FAILED,SUCCESS,FROM_CACHE,UP_TO_DATE,UNKNOWN,SKIPPED
     */
    @Serializable
    enum class Outcome(val value: kotlin.String) {
        @SerialName(value = "failed") FAILED("failed"),
        @SerialName(value = "success") SUCCESS("success"),
        @SerialName(value = "from_cache") FROM_CACHE("from_cache"),
        @SerialName(value = "up_to_date") UP_TO_DATE("up_to_date"),
        @SerialName(value = "unknown") UNKNOWN("unknown"),
        @SerialName(value = "skipped") SKIPPED("skipped");
    }
    /**
     * The avoidance outcome of this artifact transform execution with respect to performance:   * `avoided_up_to_date` - Artifact transform execution whose execution is avoided due to build incrementalism   * `avoided_from_local_cache` - Artifact transform execution whose execution is avoided due to reusing a local build cache entry   * `avoided_from_remote_cache` - Artifact transform execution whose execution is avoided due to reusing a remote build cache entry   * `executed_cacheable` - Artifact transform execution which is executed but is cacheable   * `executed_not_cacheable` - Artifact transform execution which is executed but is not cacheable   * `executed_unknown_cacheability` - Artifact transform execution which is executed and whose cacheability can not be determined   * `avoided_unknown_reason` - Artifact transform execution which was avoided for an unknown reason   * `skipped` - Skipped artifact transform execution. **This is not emitted anymore, replaced by `up_to_date`.** 
     *
     * Values: AVOIDED_UP_TO_DATE,AVOIDED_FROM_LOCAL_CACHE,AVOIDED_FROM_REMOTE_CACHE,EXECUTED_CACHEABLE,EXECUTED_NOT_CACHEABLE,EXECUTED_UNKNOWN_CACHEABILITY,AVOIDED_UNKNOWN_CACHEBILITY,AVOIDED_UNKNOWN_REASON,SKIPPED
     */
    @Serializable
    enum class AvoidanceOutcome(val value: kotlin.String) {
        @SerialName(value = "avoided_up_to_date") AVOIDED_UP_TO_DATE("avoided_up_to_date"),
        @SerialName(value = "avoided_from_local_cache") AVOIDED_FROM_LOCAL_CACHE("avoided_from_local_cache"),
        @SerialName(value = "avoided_from_remote_cache") AVOIDED_FROM_REMOTE_CACHE("avoided_from_remote_cache"),
        @SerialName(value = "executed_cacheable") EXECUTED_CACHEABLE("executed_cacheable"),
        @SerialName(value = "executed_not_cacheable") EXECUTED_NOT_CACHEABLE("executed_not_cacheable"),
        @SerialName(value = "executed_unknown_cacheability") EXECUTED_UNKNOWN_CACHEABILITY("executed_unknown_cacheability"),
        @SerialName(value = "avoided_unknown_cachebility") AVOIDED_UNKNOWN_CACHEBILITY("avoided_unknown_cachebility"),
        @SerialName(value = "avoided_unknown_reason") AVOIDED_UNKNOWN_REASON("avoided_unknown_reason"),
        @SerialName(value = "skipped") SKIPPED("skipped");
    }
    /**
     * The category of the non-cacheability reason:   * `build_cache_not_enabled` - Caching is not enabled for the build   * `disabled_to_ensure_correctness` - The artifact transform failed validation   * `not_cacheable` - Caching is not enabled for this artifact transform   * `unknown` - Reason for disabled caching is not known  `null` when the artifact transform execution is cacheable 
     *
     * Values: BUILD_CACHE_NOT_ENABLED,DISABLED_TO_ENSURE_CORRECTNESS,NOT_CACHEABLE,UNKNOWN
     */
    @Serializable
    enum class NonCacheabilityCategory(val value: kotlin.String) {
        @SerialName(value = "build_cache_not_enabled") BUILD_CACHE_NOT_ENABLED("build_cache_not_enabled"),
        @SerialName(value = "disabled_to_ensure_correctness") DISABLED_TO_ENSURE_CORRECTNESS("disabled_to_ensure_correctness"),
        @SerialName(value = "not_cacheable") NOT_CACHEABLE("not_cacheable"),
        @SerialName(value = "unknown") UNKNOWN("unknown");
    }
    /**
     * The reason why the cache artifact is rejected:   * `artifact_size_too_large` - The size of the artifact is larger than the remote build cache can accept.  The value is `null` if the transform execution is not cacheable, or if the attempt to store the artifact does not succeed. 
     *
     * Values: ARTIFACT_SIZE_TOO_LARGE
     */
    @Serializable
    enum class CacheArtifactRejectedReason(val value: kotlin.String) {
        @SerialName(value = "artifact_size_too_large") ARTIFACT_SIZE_TOO_LARGE("artifact_size_too_large");
    }
}

