/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A summary of task and artifact transform fingerprinting. `null` if Gradle version is < `5.0` or Develocity Gradle plugin version is < `2.1`.
 *
 * @param count Count of fingerprinted work units.
 * @param serialDuration Sum of all fingerprinting times of fingerprinted work units in milliseconds.
 */
@Serializable

data class GradleBuildCachePerformanceWorkUnitFingerprintingSummary (

    /* Count of fingerprinted work units. */
    @SerialName(value = "count")
    val count: kotlin.Int,

    /* Sum of all fingerprinting times of fingerprinted work units in milliseconds. */
    @SerialName(value = "serialDuration")
    val serialDuration: kotlin.Long

)

