/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Maven build options for this build.
 *
 * @param errorsEnabled Indicates whether the build is configured to produce execution error messages. See https://maven.apache.org/ref/current/maven-embedder/cli.html#errors.
 * @param maxNumberOfThreads Maximum number of threads used when executing the build. See https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3.
 * @param nonRecursiveEnabled Indicates whether the build is configured to not recurse into sub-projects. See https://maven.apache.org/ref/current/maven-embedder/cli.html#non-recursive.
 * @param noSnapshotsUpdatesEnabled Indicates whether the build is configured to suppress snapshot updates. See https://maven.apache.org/ref/current/maven-embedder/cli.html#no-snapshot-updates.
 * @param offlineModeEnabled Indicates whether the build is configured to run offline. See https://maven.apache.org/ref/current/maven-embedder/cli.html#offline.
 * @param updateSnapshotsEnabled Indicates whether the build is configured to force a check for missing releases and updated snapshots on remote repositories. See https://maven.apache.org/ref/current/maven-embedder/cli.html#update-snapshots.
 * @param batchModeEnabled Indicates whether the build is configured to run in non-interactive (batch) mode. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#batch-mode.
 * @param debugEnabled Indicates whether the build is configured to produce execution debug output. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#debug.
 * @param failAtEndEnabled Indicates whether the build is configured to only fail at the end. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-at-end.
 * @param failFastEnabled Indicates whether the build is configured to fail at the first error. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-fast.
 * @param failNeverEnabled Indicates whether the build is configured to never fail, regardless of errors produced. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-never.
 * @param laxChecksumsEnabled Indicates whether the build is configured to only warn if checksums don't match. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#lax-checksums.
 * @param rerunGoals **This property is deprecated, use `rerunGoalsEnabled` instead.** Indicates whether the build is configured to rerun goals without checking the build cache. `null` if Develocity Maven extension version is < `1.13`. See https://gradle.com/help/maven-extension-rerunning-goals. 
 * @param rerunGoalsEnabled Indicates whether the build is configured to rerun goals without checking the build cache. `null` if Develocity Maven extension version is < `1.13`. See https://gradle.com/help/maven-extension-rerunning-goals.
 * @param quietEnabled Indicates whether the build is configured to run in quiet mode. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#quiet.
 * @param strictChecksumsEnabled Indicates whether the build is configured to fail if checksums don't match. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#strict-checksums.
 */
@Serializable

data class MavenBuildOptions (

    /* Indicates whether the build is configured to produce execution error messages. See https://maven.apache.org/ref/current/maven-embedder/cli.html#errors. */
    @SerialName(value = "errorsEnabled")
    val errorsEnabled: kotlin.Boolean,

    /* Maximum number of threads used when executing the build. See https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3. */
    @SerialName(value = "maxNumberOfThreads")
    val maxNumberOfThreads: kotlin.Int,

    /* Indicates whether the build is configured to not recurse into sub-projects. See https://maven.apache.org/ref/current/maven-embedder/cli.html#non-recursive. */
    @SerialName(value = "nonRecursiveEnabled")
    val nonRecursiveEnabled: kotlin.Boolean,

    /* Indicates whether the build is configured to suppress snapshot updates. See https://maven.apache.org/ref/current/maven-embedder/cli.html#no-snapshot-updates. */
    @SerialName(value = "noSnapshotsUpdatesEnabled")
    val noSnapshotsUpdatesEnabled: kotlin.Boolean,

    /* Indicates whether the build is configured to run offline. See https://maven.apache.org/ref/current/maven-embedder/cli.html#offline. */
    @SerialName(value = "offlineModeEnabled")
    val offlineModeEnabled: kotlin.Boolean,

    /* Indicates whether the build is configured to force a check for missing releases and updated snapshots on remote repositories. See https://maven.apache.org/ref/current/maven-embedder/cli.html#update-snapshots. */
    @SerialName(value = "updateSnapshotsEnabled")
    val updateSnapshotsEnabled: kotlin.Boolean,

    /* Indicates whether the build is configured to run in non-interactive (batch) mode. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#batch-mode. */
    @SerialName(value = "batchModeEnabled")
    val batchModeEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to produce execution debug output. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#debug. */
    @SerialName(value = "debugEnabled")
    val debugEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to only fail at the end. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-at-end. */
    @SerialName(value = "failAtEndEnabled")
    val failAtEndEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to fail at the first error. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-fast. */
    @SerialName(value = "failFastEnabled")
    val failFastEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to never fail, regardless of errors produced. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#fail-never. */
    @SerialName(value = "failNeverEnabled")
    val failNeverEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to only warn if checksums don't match. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#lax-checksums. */
    @SerialName(value = "laxChecksumsEnabled")
    val laxChecksumsEnabled: kotlin.Boolean? = null,

    /* **This property is deprecated, use `rerunGoalsEnabled` instead.** Indicates whether the build is configured to rerun goals without checking the build cache. `null` if Develocity Maven extension version is < `1.13`. See https://gradle.com/help/maven-extension-rerunning-goals.  */
    @SerialName(value = "rerunGoals")
    @Deprecated(message = "This property is deprecated.")
    val rerunGoals: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to rerun goals without checking the build cache. `null` if Develocity Maven extension version is < `1.13`. See https://gradle.com/help/maven-extension-rerunning-goals. */
    @SerialName(value = "rerunGoalsEnabled")
    val rerunGoalsEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to run in quiet mode. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#quiet. */
    @SerialName(value = "quietEnabled")
    val quietEnabled: kotlin.Boolean? = null,

    /* Indicates whether the build is configured to fail if checksums don't match. `null` if capturing is not possible. See https://maven.apache.org/ref/current/maven-embedder/cli.html#strict-checksums. */
    @SerialName(value = "strictChecksumsEnabled")
    val strictChecksumsEnabled: kotlin.Boolean? = null

)

