/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the local and remote build caches used in the build, if it is configured in the build. `null` if the build cache configuration cannot be captured (e.g. very early build failure).
 *
 * @param overhead 
 * @param local 
 * @param remote 
 */
@Serializable

data class MavenBuildCachePerformanceBuildCaches (

    @SerialName(value = "overhead")
    val overhead: MavenBuildCachePerformanceBuildCacheOverhead,

    @SerialName(value = "local")
    val local: MavenBuildCachePerformanceBuildCacheLocalInfo? = null,

    @SerialName(value = "remote")
    val remote: MavenBuildCachePerformanceBuildCacheRemoteInfo? = null

)

