/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the remote build cache used in the build, if it is configured in the build. `null` if the remote build cache is not configured.
 *
 * @param isEnabled Indicates whether the remote build cache is enabled.
 * @param isPushEnabled Indicates whether pushing to the remote build cache is enabled. `null` if the remote build cache is disabled.
 * @param isDisabledDueToError Indicates whether the remote build cache is disabled during the build due to an error occurring in loading or storing remote build cache entries. `null` if the remote build cache is disabled.
 * @param url URL of the remote build cache. `null` if the remote build cache is disabled.
 */
@Serializable

data class MavenBuildCachePerformanceBuildCacheRemoteInfo (

    /* Indicates whether the remote build cache is enabled. */
    @SerialName(value = "isEnabled")
    val isEnabled: kotlin.Boolean,

    /* Indicates whether pushing to the remote build cache is enabled. `null` if the remote build cache is disabled. */
    @SerialName(value = "isPushEnabled")
    val isPushEnabled: kotlin.Boolean? = null,

    /* Indicates whether the remote build cache is disabled during the build due to an error occurring in loading or storing remote build cache entries. `null` if the remote build cache is disabled. */
    @SerialName(value = "isDisabledDueToError")
    val isDisabledDueToError: kotlin.Boolean? = null,

    /* URL of the remote build cache. `null` if the remote build cache is disabled. */
    @SerialName(value = "url")
    val url: kotlin.String? = null

)

