/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about dependency resolution.
 *
 * @param serialDependencyResolutionTime The total cumulative time, in milliseconds, spent resolving dependencies. The process of resolving a dependency involves fetching metadata from remote repositories, determining the appropriate version to use, and ultimately fetching the dependency artifact.
 * @param networkRequestCount This represents the total count of network requests made during configuration resolution.
 * @param serialNetworkRequestTime The duration in milliseconds representing the sum of times for potentially parallel network requests. It does not reflect wall clock time but offers a rough estimation of network activity.
 * @param wallClockNetworkRequestTime The estimate in milliseconds representing the wall clock time spent on network requests during the current build. It is calculated by comparing the critical path of project executions with and without network requests, converted to wall clock time.
 * @param fileDownloadSize The total number of bytes downloaded for dependencies. It accounts only for the bytes of the files (e.g. POMs, JARs) downloaded and not the total network transfer.
 * @param fileDownloadCount The total number of successfully downloaded files.
 */
@Serializable

data class MavenDependencyResolution (

    /* The total cumulative time, in milliseconds, spent resolving dependencies. The process of resolving a dependency involves fetching metadata from remote repositories, determining the appropriate version to use, and ultimately fetching the dependency artifact. */
    @SerialName(value = "serialDependencyResolutionTime")
    val serialDependencyResolutionTime: kotlin.Long,

    /* This represents the total count of network requests made during configuration resolution. */
    @SerialName(value = "networkRequestCount")
    val networkRequestCount: kotlin.Long,

    /* The duration in milliseconds representing the sum of times for potentially parallel network requests. It does not reflect wall clock time but offers a rough estimation of network activity. */
    @SerialName(value = "serialNetworkRequestTime")
    val serialNetworkRequestTime: kotlin.Long,

    /* The estimate in milliseconds representing the wall clock time spent on network requests during the current build. It is calculated by comparing the critical path of project executions with and without network requests, converted to wall clock time. */
    @SerialName(value = "wallClockNetworkRequestTime")
    val wallClockNetworkRequestTime: kotlin.Long,

    /* The total number of bytes downloaded for dependencies. It accounts only for the bytes of the files (e.g. POMs, JARs) downloaded and not the total network transfer. */
    @SerialName(value = "fileDownloadSize")
    val fileDownloadSize: kotlin.Long,

    /* The total number of successfully downloaded files. */
    @SerialName(value = "fileDownloadCount")
    val fileDownloadCount: kotlin.Long

)

