/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A summary of goal fingerprinting. Fingerprinted goals are part of the `goalExecution.avoidedGoals` or `goalExecution.executedGoals` buckets.
 *
 * @param count Count of fingerprinted goals.
 * @param serialDuration Sum of all fingerprinting times of fingerprinted goals in milliseconds.
 */
@Serializable

data class MavenBuildCachePerformanceGoalFingerprintingSummary (

    /* Count of fingerprinted goals. */
    @SerialName(value = "count")
    val count: kotlin.Int,

    /* Sum of all fingerprinting times of fingerprinted goals in milliseconds. */
    @SerialName(value = "serialDuration")
    val serialDuration: kotlin.Long

)

