/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the local build cache used in the build, if it is configured in the build. `null` if the local build cache is not configured.
 *
 * @param isEnabled Indicates whether the local build cache is enabled.
 * @param isPushEnabled Indicates whether pushing to the local build cache is enabled. `null` if the local build cache is disabled.
 * @param isDisabledDueToError Indicates whether the local cache is disabled due to an error occurring in loading or storing local build cache entries. `null` if the local build cache is disabled.
 * @param directory Location of the local build cache. Can be relative or absolute depending on its value. `null` if the local build cache is disabled.
 */
@Serializable

data class MavenBuildCachePerformanceBuildCacheLocalInfo (

    /* Indicates whether the local build cache is enabled. */
    @SerialName(value = "isEnabled")
    val isEnabled: kotlin.Boolean,

    /* Indicates whether pushing to the local build cache is enabled. `null` if the local build cache is disabled. */
    @SerialName(value = "isPushEnabled")
    val isPushEnabled: kotlin.Boolean? = null,

    /* Indicates whether the local cache is disabled due to an error occurring in loading or storing local build cache entries. `null` if the local build cache is disabled. */
    @SerialName(value = "isDisabledDueToError")
    val isDisabledDueToError: kotlin.Boolean? = null,

    /* Location of the local build cache. Can be relative or absolute depending on its value. `null` if the local build cache is disabled. */
    @SerialName(value = "directory")
    val directory: kotlin.String? = null

)

