/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Maven work unit.
 *
 * @param groupId The Maven groupId.
 * @param artifactId The Maven artifactId.
 * @param goalName The Maven goal name.
 * @param executionId The execution id of the goal.
 */
@Serializable

data class MavenWorkUnit (

    /* The Maven groupId. */
    @SerialName(value = "groupId")
    val groupId: kotlin.String,

    /* The Maven artifactId. */
    @SerialName(value = "artifactId")
    val artifactId: kotlin.String,

    /* The Maven goal name. */
    @SerialName(value = "goalName")
    val goalName: kotlin.String,

    /* The execution id of the goal. */
    @SerialName(value = "executionId")
    val executionId: kotlin.String

)

