/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Maven module.
 *
 * @param name The name of the module.
 * @param groupId The group ID of the module.
 * @param artifactId The artifact ID of the module.
 * @param version The version of the module.
 * @param parent The index of the parent of this Maven module in the MavenModules array. `null` if this module has no parent (i.e. top level project).
 */
@Serializable

data class MavenModule (

    /* The name of the module. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The group ID of the module. */
    @SerialName(value = "groupId")
    val groupId: kotlin.String,

    /* The artifact ID of the module. */
    @SerialName(value = "artifactId")
    val artifactId: kotlin.String,

    /* The version of the module. */
    @SerialName(value = "version")
    val version: kotlin.String,

    /* The index of the parent of this Maven module in the MavenModules array. `null` if this module has no parent (i.e. top level project). */
    @SerialName(value = "parent")
    val parent: kotlin.Int? = null

)

