/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Build Cache Node configuration description.
 *
 * @param enabled Indicates if the Build Cache Node is enabled.
 * @param replication 
 */
@Serializable

data class NodeConfiguration (

    /* Indicates if the Build Cache Node is enabled. */
    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "replication")
    val replication: ReplicationConfiguration? = null

)

