/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Information about the current and available page of elements. Pages are returned from list operations which could contain a lot of elements. One page contains a subset of the available elements. API users can retrieve all pages in order to retrieve all of the available elements. 
 *
 * @param number The index of the current page. Page indexes start at zero.
 * @param propertySize The number of elements in the current page.
 * @param totalPages The total number of pages.
 * @param totalElements The total number of elements across all pages.
 */
@Serializable

data class PageMetadata (

    /* The index of the current page. Page indexes start at zero. */
    @SerialName(value = "number")
    val number: kotlin.Int,

    /* The number of elements in the current page. */
    @SerialName(value = "size")
    val propertySize: kotlin.Int,

    /* The total number of pages. */
    @SerialName(value = "totalPages")
    val totalPages: kotlin.Int,

    /* The total number of elements across all pages. */
    @SerialName(value = "totalElements")
    val totalElements: kotlin.Int

)

