/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param pageNumber The index of the page to retrieve. The first page's index is zero. 
 * @param pageSize The maximum number of elements to include in the fetched page.
 */
@Serializable

data class PageQuery (

    /* The index of the page to retrieve. The first page's index is zero.  */
    @SerialName(value = "pageNumber")
    val pageNumber: kotlin.Int? = 0,

    /* The maximum number of elements to include in the fetched page. */
    @SerialName(value = "pageSize")
    val pageSize: kotlin.Int? = null

)

