/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A container for a project ID.
 *
 * @param id The unique identifier for the project. Must not contain whitespace.
 */
@Serializable

data class ProjectReference (

    /* The unique identifier for the project. Must not contain whitespace. */
    @SerialName(value = "id")
    val id: kotlin.String

)

