/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Cached data replication configuration description. May be `null` if replication is not configured.
 *
 * @param source The name of the Build Cache Node which is the source of data.
 * @param preemptive Indicates if preemptive replication is enabled from the source.
 */
@Serializable

data class ReplicationConfiguration (

    /* The name of the Build Cache Node which is the source of data. */
    @SerialName(value = "source")
    val source: kotlin.String,

    /* Indicates if preemptive replication is enabled from the source. */
    @SerialName(value = "preemptive")
    val preemptive: kotlin.Boolean

)

