/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Test Distribution pool-specific agent registration key.
 *
 * @param key The agent API key.
 * @param description Description of the registration key to help identify it later.
 */
@Serializable

data class TestDistributionAgentPoolRegistrationKey (

    /* The agent API key. */
    @SerialName(value = "key")
    val key: kotlin.String,

    /* Description of the registration key to help identify it later. */
    @SerialName(value = "description")
    val description: kotlin.String? = null

)

