/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: PASSED,FAILED,SKIPPED,FLAKY,NOT_SELECTED
 */
@Serializable
enum class TestOutcome(val value: kotlin.String) {

    @SerialName(value = "passed")
    PASSED("passed"),

    @SerialName(value = "failed")
    FAILED("failed"),

    @SerialName(value = "skipped")
    SKIPPED("skipped"),

    @SerialName(value = "flaky")
    FLAKY("flaky"),

    @SerialName(value = "notSelected")
    NOT_SELECTED("notSelected");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TestOutcome) "$data" else null

        /**
         * Returns a valid [TestOutcome] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TestOutcome? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

