/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * An agent pool configuration.
 *
 * @param id The unique identifier of the agent pool.
 * @param name The alias or display name of the agent pool.
 * @param minimumSize 
 * @param maximumSize 
 * @param orderIndex The order in which the agent pool is considered for allocation. Lower values are considered first.
 * @param capabilities 
 * @param restrictAccessToProjectGroups Controls whether this pool can be used by everyone, or only the assigned project groups. A `true` value implies that `projectGroupIds` is present and has at least one entry. Conversely, a `false` value implies that `projectGroupIds` is empty. 
 * @param projectGroupIds Controls which project groups can use this pool. If it is empty, then `restrictAccessToProjectGroups` must be `false`. Conversely, if it has values then `restrictAccessToProjectGroups` must be `true`. 
 */
@Serializable

data class TestDistributionAgentPoolConfigurationWithId (

    /* The unique identifier of the agent pool. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* The alias or display name of the agent pool. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "minimumSize")
    val minimumSize: kotlin.Int,

    @SerialName(value = "maximumSize")
    val maximumSize: kotlin.Int,

    /* The order in which the agent pool is considered for allocation. Lower values are considered first. */
    @SerialName(value = "orderIndex")
    val orderIndex: kotlin.Int,

    @SerialName(value = "capabilities")
    val capabilities: kotlin.collections.List<kotlin.String>,

    /* Controls whether this pool can be used by everyone, or only the assigned project groups. A `true` value implies that `projectGroupIds` is present and has at least one entry. Conversely, a `false` value implies that `projectGroupIds` is empty.  */
    @SerialName(value = "restrictAccessToProjectGroups")
    val restrictAccessToProjectGroups: kotlin.Boolean? = false,

    /* Controls which project groups can use this pool. If it is empty, then `restrictAccessToProjectGroups` must be `false`. Conversely, if it has values then `restrictAccessToProjectGroups` must be `true`.  */
    @SerialName(value = "projectGroupIds")
    val projectGroupIds: kotlin.collections.List<kotlin.String>? = null

)

