/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * **This class is deprecated. Migrate to pool-specific agent registration keys instead.** A Test Distribution agent API key prefix. 
 *
 * @param keyPrefix The agent API key.
 * @param generatedAt 
 * @param description Description of the API key, such as the agent pool where it will be used, to help identify it later.
 * @param lastUsedAt 
 * @param lastUsedBy 
 * @param revokedAt 
 */
@Serializable
@Deprecated(message = "This schema is deprecated.")

data class TestDistributionApiKeyPrefix (

    /* The agent API key. */
    @SerialName(value = "keyPrefix")
    val keyPrefix: kotlin.String,

    @SerialName(value = "generatedAt")
    val generatedAt: kotlin.String,

    /* Description of the API key, such as the agent pool where it will be used, to help identify it later. */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "lastUsedAt")
    val lastUsedAt: kotlin.String? = null,

    @SerialName(value = "lastUsedBy")
    val lastUsedBy: kotlin.String? = null,

    @SerialName(value = "revokedAt")
    val revokedAt: kotlin.String? = null

)

