/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param container Must be the fully qualified name of the test container to query. May not contain any wildcards.
 * @param testOutcomes Allows restricting the search to tests that had at least one instance of the given outcome.
 * @param query A query for filtering tests, written in the Develocity advanced search query language See: https://gradle.com/help/advanced-search 
 * @param limit The maximum number of test outcomes to query.
 * @param include Controls which optional fields are included in the response.
 */
@Serializable

data class TestCasesQuery (

    /* Must be the fully qualified name of the test container to query. May not contain any wildcards. */
    @SerialName(value = "container")
    val container: kotlin.String,

    /* Allows restricting the search to tests that had at least one instance of the given outcome. */
    @SerialName(value = "testOutcomes")
    val testOutcomes: kotlin.collections.List<@Contextual TestOutcome>,

    /* A query for filtering tests, written in the Develocity advanced search query language See: https://gradle.com/help/advanced-search  */
    @SerialName(value = "query")
    val query: kotlin.String,

    /* The maximum number of test outcomes to query. */
    @SerialName(value = "limit")
    val limit: kotlin.Int? = 100,

    /* Controls which optional fields are included in the response. */
    @SerialName(value = "include")
    val include: kotlin.collections.List<@Contextual TestIncludeFields>? = null

)

