/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A Test Distribution pool-specific agent registration key prefix.
 *
 * @param keyPrefix The registration key prefix.
 * @param createdAt When the key was created
 * @param description Description of the registration key to help identify it later.
 * @param lastUsedAt When the key was last used
 * @param lastUsedBy Who used the key last
 * @param revokedAt When the key was revoked, a non-null value implies that the key is revoked and can no longer be used to authenticate.
 */
@Serializable

data class TestDistributionAgentPoolRegistrationKeyPrefix (

    /* The registration key prefix. */
    @SerialName(value = "keyPrefix")
    val keyPrefix: kotlin.String,

    /* When the key was created */
    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    /* Description of the registration key to help identify it later. */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    /* When the key was last used */
    @SerialName(value = "lastUsedAt")
    val lastUsedAt: kotlin.String? = null,

    /* Who used the key last */
    @SerialName(value = "lastUsedBy")
    val lastUsedBy: kotlin.String? = null,

    /* When the key was revoked, a non-null value implies that the key is revoked and can no longer be used to authenticate. */
    @SerialName(value = "revokedAt")
    val revokedAt: kotlin.String? = null

)

