/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport", "DEPRECATION"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * **This class is deprecated. Migrate to pool-specific agent registration keys instead.** A list of Test Distribution agent API key prefixes. 
 *
 * @param content 
 */
@Serializable
@Deprecated(message = "This schema is deprecated.")

data class TestDistributionApiKeyPrefixPage (

    @SerialName(value = "content")
    val content: kotlin.collections.List<TestDistributionApiKeyPrefix>

)

