/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of agent pools.
 *
 * @param content A list of agent pool IDs.
 */
@Serializable

data class TestDistributionAgentPoolPage (

    /* A list of agent pool IDs. */
    @SerialName(value = "content")
    val content: kotlin.collections.List<TestDistributionAgentPoolConfigurationWithId>

)

