/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A distribution of outcomes.
 *
 * @param passed The number of 'Passed' outcomes.
 * @param failed The number of 'Failed' outcomes.
 * @param skipped The number of 'Skipped' outcomes.
 * @param flaky The number of 'Flaky' outcomes.
 * @param notSelected The number of 'Not Selected' outcomes.
 * @param total The total number of outcomes.
 */
@Serializable

data class TestOutcomeDistribution (

    /* The number of 'Passed' outcomes. */
    @SerialName(value = "passed")
    val passed: kotlin.Int,

    /* The number of 'Failed' outcomes. */
    @SerialName(value = "failed")
    val failed: kotlin.Int,

    /* The number of 'Skipped' outcomes. */
    @SerialName(value = "skipped")
    val skipped: kotlin.Int,

    /* The number of 'Flaky' outcomes. */
    @SerialName(value = "flaky")
    val flaky: kotlin.Int,

    /* The number of 'Not Selected' outcomes. */
    @SerialName(value = "notSelected")
    val notSelected: kotlin.Int,

    /* The total number of outcomes. */
    @SerialName(value = "total")
    val total: kotlin.Int

)

