/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A list of Test Distribution pool-specific agent registration key prefixes.
 *
 * @param content 
 */
@Serializable

data class TestDistributionAgentPoolRegistrationKeyPrefixPage (

    @SerialName(value = "content")
    val content: kotlin.collections.List<TestDistributionAgentPoolRegistrationKeyPrefix>

)

