/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The status of an agent pool.
 *
 * @param id The unique identifier of the agent pool.
 * @param name The alias or display name of the agent pool.
 * @param minimumSize 
 * @param maximumSize 
 * @param connectedAgents 
 * @param idleAgents 
 * @param desiredAgents 
 */
@Serializable

data class TestDistributionAgentPoolStatus (

    /* The unique identifier of the agent pool. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* The alias or display name of the agent pool. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "minimumSize")
    val minimumSize: kotlin.Int,

    @SerialName(value = "maximumSize")
    val maximumSize: kotlin.Int,

    @SerialName(value = "connectedAgents")
    val connectedAgents: kotlin.Int,

    @SerialName(value = "idleAgents")
    val idleAgents: kotlin.Int,

    @SerialName(value = "desiredAgents")
    val desiredAgents: kotlin.Int

)

