/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.ebay.plugins.metrics.develocity.service.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Contains a work unit.  Only one of the properties is set, representing the build tool used for the build. 
 *
 * @param bazel 
 * @param gradle 
 * @param maven 
 */
@Serializable

data class TestWorkUnit (

    @SerialName(value = "bazel")
    val bazel: BazelWorkUnit? = null,

    @SerialName(value = "gradle")
    val gradle: GradleWorkUnit? = null,

    @SerialName(value = "maven")
    val maven: MavenWorkUnit? = null

)

