name: PR Build
on:
  pull_request:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Plugin
        run: ./gradlew build
      - name: Build Sample
        working-directory: sample
        run: ./gradlew build
