name: PR Build
on: [push]
jobs:
  gradle:
    runs-on: ebaymobile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Plugin
        run: ./gradlew build
      - name: Build Sample
        working-directory: sample
        run: ./gradlew build
